version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pgsql_local
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: employees_db
    ports:
      - "5433:5432"
    networks:
      - globalnet

networks:
  globalnet:
    external: true
